# Generated by Django 4.2.8 on 2025-10-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_selenium', models.BooleanField(default=False)),
                ('rate_limit', models.IntegerField(default=10, help_text='Requests per minute')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority scraped first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Portal',
                'verbose_name_plural': 'Job Portals',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technical'), ('NON_TECHNICAL', 'Non-Technical'), ('BOTH', 'Both')], default='BOTH', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('ALL', 'All Jobs'), ('REMOTE', 'Remote'), ('FREELANCE', 'Freelance'), ('FULL_TIME', 'Full Time'), ('HYBRID', 'Hybrid')], default='ALL', max_length=20)),
                ('time_filter', models.CharField(choices=[('24H', 'Last 24 Hours'), ('3D', 'Last 3 Days'), ('7D', 'Last 7 Days'), ('ALL', 'All Time')], default='ALL', max_length=10)),
                ('location', models.CharField(choices=[('ALL', 'All Locations'), ('USA', 'USA'), ('UK', 'UK')], default='ALL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_portals', models.ManyToManyField(related_name='saved_filters', to='dashboard.jobportal')),
                ('keywords', models.ManyToManyField(related_name='saved_filters', to='dashboard.keyword')),
            ],
            options={
                'verbose_name': 'Saved Filter',
                'verbose_name_plural': 'Saved Filters',
                'ordering': ['-last_used', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScraperRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_jobs_scraped', models.IntegerField(default=0)),
                ('successful_scrapes', models.IntegerField(default=0)),
                ('failed_scrapes', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('saved_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_runs', to='dashboard.savedfilter')),
            ],
            options={
                'verbose_name': 'Scraper Run',
                'verbose_name_plural': 'Scraper Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
