# Generated by Django 4.2.25 on 2025-11-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfilter',
            name='time_filter',
            field=models.CharField(choices=[('24H', 'Last 24 Hours'), ('3D', 'Last 3 Days'), ('7D', 'Last 7 Days'), ('ALL', 'All Time')], default='24H', max_length=10),
        ),
    ]
