# Generated by Django 4.2.8 on 2025-10-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500, unique=True)),
                ('company_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('company_size', models.CharField(blank=True, max_length=20, null=True)),
                ('company_domain', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin_company_id', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_company_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('cache_valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company Cache',
                'verbose_name_plural': 'Company Cache',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='ScraperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('exception_traceback', models.TextField(blank=True, null=True)),
                ('url_scraped', models.URLField(blank=True, max_length=2000, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.jobportal')),
                ('scraper_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.scraperrun')),
            ],
            options={
                'verbose_name': 'Scraper Log',
                'verbose_name_plural': 'Scraper Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('company_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('company_size', models.CharField(choices=[('SMALL', 'Small (1-50)'), ('MEDIUM', 'Medium (51-250)'), ('LARGE', 'Large (251-1000)'), ('ENTERPRISE', 'Enterprise (1000+)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('market', models.CharField(choices=[('USA', 'USA'), ('UK', 'UK'), ('OTHER', 'Other')], max_length=10)),
                ('job_link', models.URLField(max_length=2000, unique=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=500)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=200, null=True)),
                ('is_exported_to_sheets', models.BooleanField(default=False)),
                ('sheets_row_number', models.IntegerField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraper_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='dashboard.scraperrun')),
                ('source_job_portal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='dashboard.jobportal')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence in data accuracy (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_makers', to='scraper.job')),
            ],
            options={
                'verbose_name': 'Decision Maker',
                'verbose_name_plural': 'Decision Makers',
                'ordering': ['job', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'job_title'], name='scraper_job_company_2b2cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source_job_portal', 'posted_date'], name='scraper_job_source__6ad370_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['market', 'location'], name='scraper_job_market_e31ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionmaker',
            index=models.Index(fields=['company', 'name'], name='scraper_dec_company_e73d2a_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionmaker',
            index=models.Index(fields=['job', 'title'], name='scraper_dec_job_id_5da4f3_idx'),
        ),
    ]
