# Generated by Django 4.2.25 on 2025-11-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_exported_to_sheets',
        ),
        migrations.RemoveField(
            model_name='job',
            name='sheets_row_number',
        ),
    ]
