# Generated by Django 4.2.25 on 2025-11-08 06:47

from django.db import migrations, models


def populate_job_field(apps, schema_editor):
    Job = apps.get_model('scraper', 'Job')
    Keyword = apps.get_model('dashboard', 'Keyword')

    technical_terms = [
        (kw.name or '').strip().lower()
        for kw in Keyword.objects.filter(category='TECHNICAL', is_active=True)
    ]
    non_technical_terms = [
        (kw.name or '').strip().lower()
        for kw in Keyword.objects.filter(category='NON_TECHNICAL', is_active=True)
    ]
    both_terms = [
        (kw.name or '').strip().lower()
        for kw in Keyword.objects.filter(category='BOTH', is_active=True)
    ]

    def classify(text: str) -> str:
        if not text:
            return 'UNKNOWN'
        lowered = text.lower()
        matches = set()
        for term in technical_terms:
            if term and term in lowered:
                matches.add('TECHNICAL')
                break
        for term in non_technical_terms:
            if term and term in lowered:
                matches.add('NON_TECHNICAL')
                break
        for term in both_terms:
            if term and term in lowered:
                matches.update({'TECHNICAL', 'NON_TECHNICAL'})
                break
        if not matches:
            return 'UNKNOWN'
        if matches == {'TECHNICAL'}:
            return 'TECHNICAL'
        if matches == {'NON_TECHNICAL'}:
            return 'NON_TECHNICAL'
        return 'BOTH'

    jobs = Job.objects.all().only('id', 'job_title', 'job_description')
    for job in jobs.iterator():
        text = f"{job.job_title or ''} {job.job_description or ''}"
        job.job_field = classify(text)
        job.save(update_fields=['job_field'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_job_is_exported_to_sheets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_field',
            field=models.CharField(choices=[('TECHNICAL', 'Technical'), ('NON_TECHNICAL', 'Non-Technical'), ('BOTH', 'Both'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.RunPython(populate_job_field, reverse_code=noop),
    ]
