# Generated by Django 4.2.8 on 2025-10-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('spreadsheet_id', models.CharField(max_length=255)),
                ('worksheet_name', models.CharField(default='Jobs', max_length=255)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_export', models.BooleanField(default=True, help_text='Automatically export new jobs')),
                ('include_headers', models.BooleanField(default=True)),
                ('total_rows_exported', models.IntegerField(default=0)),
                ('last_export_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Sheet Config',
                'verbose_name_plural': 'Google Sheet Configs',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('jobs_exported', models.IntegerField(default=0)),
                ('rows_added', models.IntegerField(default=0)),
                ('rows_updated', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sheet_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_history', to='google_sheets.googlesheetconfig')),
            ],
            options={
                'verbose_name': 'Export History',
                'verbose_name_plural': 'Export Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
